version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn package
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest